### ISSUE TITLE
react-relay RelayModernStore (UNSTABLE_DO_NOT_USE_getDataID) v5.0.0

### ISSUE THREAD

**Issue by morrys** [morrys/react-relay-offline#10]
adapt the library to the 5.0.0 relay version

**Comment by amiinous** [comment]
This library does not work all with Relay 5.0.0?

**Comment by morrys** [comment]
Hi amiinous,
the library works with version 5.0.0, in fact in the package.json I put as peerDependencies "react-relay": "> = 3.0.0".

In version 5.0.0 of relays a new parameter was experimentally added in RelayModernStore and this issue I opened as a reminder to adapt the react-relay-offline store once it becomes stable.

**Comment by morrys** [comment]
Hi @amiinous,
with the new version of react-relay-offline I added new features and also resolved compatibility with the store to version 5.0.0.

https://github.com/morrys/react-relay-offline/releases/tag/v0.7.0

If you find any problems, open a new issue as well.

Lorenzo
