### ISSUE TITLE
createFragmentContainer in v3

### ISSUE THREAD

**Issue by matt-dalton** [morrys/react-relay-offline#100]
We've (finally) tried to upgrade to version 3. It seems we can no longer import `createFragmentContainer` from `react-relay-offline`. Has this now been completely removed?

I saw in the release notes that the Query HOC has been removed, but the fragment container is significantly harder for us to migrate off in one go (we'd have to refactor basically every component). Do we need to switch everything to hooks to upgrade to v3 (and hence relay 10)?

**Comment by morrys** [comment]
Hi @matt-dalton,
i removed the import from react-relay-offline but it is still possible to use it through react-relay.

Fragments do not have specific logic for offline management.

Let me know if you have any problems using them 👍

**Comment by matt-dalton** [comment]
Ah OK perfect - that gives us a workaround 👍

Is it also OK to import `graphql` from react-relay directly? Presumably there's no offline-specific logic there either

**Comment by matt-dalton** [comment]
...also - presumably it's the same situation for createPaginationContainer?

**Comment by morrys** [comment]
Yes 👍

**Comment by matt-dalton** [comment]
Brilliant - thanks for such a quick response 👌🏻
