### ISSUE TITLE
Support relay-runtime v13

### ISSUE THREAD

**Issue by morrys** [morrys/react-relay-offline#109]

**Comment by giautm** [comment]
Hi, have you done anything for this issue?

**Comment by giautm** [comment]
Not-related, but do you have any plan to deprecated the package `relay-tools/relay-hooks`? due to it was supported by react-relay, then will easier to upgrade other packages.

**Comment by morrys** [comment]
relay-hooks will be deprecated when its usage decreases and Suspense will become the standard for all

**Comment by giautm** [comment]
I don't want to use relay-hooks, because react-relay has every I need. But, I have to use them because react-relay-offline required it.

**Comment by morrys** [comment]
Now the priority is to update react-relay-offline to the new compiler.

Later, I will consider deprecating relay-hooks in react-relay-offline

**Comment by morrys** [comment]
resolved with react-relay-offline v6.0.0 https://github.com/morrys/react-relay-offline/releases/tag/v6.0.0

**Comment by justindomingue** [comment]
> Now the priority is to update react-relay-offline to the new compiler.
> 
> Later, I will consider deprecating relay-hooks in react-relay-offline

any updates on deprecating relay-hooks?
