### ISSUE TITLE
Include an implementation of fetchQuery to rehydrate store.

### ISSUE THREAD

**Issue by jckw** [morrys/react-relay-offline#16]
`react-relay`'s fetchQuery function does not work well with the store, causing RelayRecordSourceMutator errors:

```
RelayRecordSourceMutator#create(): Cannot create a record with id 
```

To fix this, this library should implement a modified version of fetchQuery which rehydrates the store before making the query.

Something like this seems to do the job: 

```
import { fetchQuery as relayFetchQuery } from 'react-relay-offline'

async function fetchQuery(...args) {
    const [environment] = args

    if (!environment.isRestored()) {
        await environment.restore()
    }

    return relayFetchQuery(...args)
}
```

**Comment by morrys** [comment]
The change was released with version [0.10.0](https://github.com/morrys/react-relay-offline/releases/tag/v0.10.0)

Let me know if you encounter any new problems :)
