### ISSUE TITLE
Pass an `offline` prop to QueryRenderer render function.

### ISSUE THREAD

**Issue by jckw** [morrys/react-relay-offline#19]
Much like the `cached: boolean` prop is passed to the render function of the QueryRenderer, it would be useful to have a `offline: boolean` prop that indicates whether the environment is offline. 

Although this can be done with `environment.isOffline()`, this means users depend on this being the same logic as is used by the [`lookupInStore` function](https://github.com/morrys/react-relay-offline/blob/master/src/ReactRelayQueryFetcher.ts#L37) so they are bound to a specific version of this library.

**Comment by morrys** [comment]
hi @jckw,
I released version [2.3.0](https://github.com/morrys/react-relay-offline/releases/tag/v2.3.0) including this issue.
