### ISSUE TITLE
QueryRendererOffline on RN: "Text strings must be rendered within a <Text> component"

### ISSUE THREAD

**Issue by patrick-samy** [morrys/react-relay-offline#20]
Hi there,

I've been able to set up my Relay environment with `react-relay-offline` and perform requests without any issues.

However, when I switched my top-level component to use QueryRendererOffline, I started getting the following error:
<img width="323" alt="Screen Shot 2019-09-11 at 14 15 07" src="https://user-images.githubusercontent.com/716488/64696416-a0d8e100-d49e-11e9-918a-fc1a66091532.png">

Here is the simplified code:
[https://gist.github.com/patrick-samy/1b4e02010af9a38d040c0c5a9066a3ca](https://gist.github.com/patrick-samy/1b4e02010af9a38d040c0c5a9066a3ca)

Any suggestions?

Cheers!

**Comment by sibelius** [comment]
you are rendering a text without a <Text> component

not a react-relay-offline issue

**Comment by patrick-samy** [comment]
@sibelius But even if I simply render an empty `View` in the `render` method of `QueryRenderer`, I get the error.

Also, if I use the relay-runtime `QueryRenderer`, no issue.

**Comment by sibelius** [comment]
The default loading component only works on web

https://github.com/morrys/react-relay-offline/blob/master/src/QueryRendererOffline.tsx#L13

we should render null instead of a `div`

care to send a PR?

**Comment by patrick-samy** [comment]
For sure, I couldn't find an example of native-specific component in the codebase though.

How would you test for react native? `try...catch`?

**Comment by sibelius** [comment]
I think it's better to render `null` instead of a default LoadingView

**Comment by morrys** [comment]
The loading component is useful because in the queryrender the rehydration (if not previously done) of the store is managed.
https://github.com/morrys/react-relay-offline/blob/master/src/QueryRendererOffline.tsx#L11

At the beginning I used null as default, but this also gave problems in react-native.

If we find a definitive solution we integrate it :)

**Comment by morrys** [comment]
If you prefer you can try using `useRestore` at the beginning of your application and avoid the loadingComponent
