### ISSUE TITLE
`retry` should check if environment is online.

### ISSUE THREAD

**Issue by jckw** [morrys/react-relay-offline#21]
Occasionally it is useful to have a "Try again" button when we go offline and do not have a cached version. This can be pressed by the user when they come back online in order to retry the query.

In order to do this, the `retry` prop (from the QueryRenderer) must be used. However, when the device is offline and QR is rendered, [`retry === null`](https://github.com/morrys/react-relay-offline/blob/master/src/hooks/useQuery.ts#L106).

A better solution would be to check if the environment is online in every retry function, so that `retry` is never null. This would be used in [useQuery](https://github.com/morrys/react-relay-offline/blob/master/src/hooks/useQuery.ts#L99).

For example, in getResult we could do:
```
if (environment.isOnline()) {
  renderProps.retry = () => {
    setHooksProps(execute(props.environment, props.query, props.variables));
  }
}
```

**Comment by morrys** [comment]
In the absence of data in the cache in the offline state, perhaps it is more correct to value both the error and retry properties.

**Comment by jckw** [comment]
I think it would be better to always have a `retry` function like the one given above. Lots of applications use it as a "refresh" method, e.g. pull-to-refresh triggers `retry`.

That way, even if we have a value in the store, it is easy to get the latest value once we have a network connection.
