### ISSUE TITLE
Using with Next.js

### ISSUE THREAD

**Issue by kmjennison** [morrys/react-relay-offline#23]
Do you have any docs or examples of how to use this with [Next.js](https://github.com/zeit/next.js)?

Here's [Next's example](https://github.com/zeit/next.js/tree/canary/examples/with-relay-modern) using Relay, and the [relevant environment files are in `lib`](https://github.com/zeit/next.js/tree/canary/examples/with-relay-modern).

Thanks!

**Comment by morrys** [comment]
Hi @kmjennison,
no, at the moment there are no examples in nextjs: / the priority is to support version 6 of react-relay and on improving performance.

for anyone who wants and has time to create the example project, I'm available to answer questions or help solve problems.

**Comment by morrys** [comment]
the project can be integrated into this repository:
[offline-examples](https://github.com/morrys/offline-examples)

**Comment by sibelius** [comment]
@kmjennison what is the missing piece for next?

**Comment by kmjennison** [comment]
@morrys Ok, thanks!

@sibelius I'm not sure if there's a missing piece or not, but my initial attempt to integrate react-relay-offline is running into some problems. Next.js's Relay integration [creates a store](https://github.com/zeit/next.js/blob/canary/examples/with-relay-modern/lib/createRelayEnvironment.js#L25) with server-side fetched data and [passes it in context](https://github.com/zeit/next.js/blob/canary/examples/with-relay-modern/lib/withData.js#L50). With `react-relay-offline`, the server-side environment's store is empty, so server-side rendering doesn't work.

[Here's](https://github.com/kmjennison/nextjs-demo/tree/899c3d8c780784d5edd805dbd0209dd4d5858ecf/lib) the code I was trying out (there's some `react-relay-offline` code commented out in createRelayEnvironment.js). I'm guessing I'm just missing something. I'll work on it more but welcome any tips if you have them.

**Comment by sibelius** [comment]
why env is empty?

**Comment by kmjennison** [comment]
It looks like the `react-relay-offline` store doesn't persist [the records passed to it here](https://github.com/kmjennison/nextjs-demo/blob/899c3d8c780784d5edd805dbd0209dd4d5858ecf/lib/createRelayEnvironment.js#L44). Calling `store.getSource().toJSON()` immediately after instantiating the store returns an empty object. With `relay-runtime`'s Store, it returns the records.

So, it's probably some difference in implementation between [the `@wora/relay-store` Store](https://github.com/morrys/wora/blob/91f6751e0c89baf5a224433bfab61220db18815f/packages/relay-store/src/Store.ts) and [ the `react-runtime` v5 Store](https://github.com/facebook/relay/blob/50d5432f71ec5570ad5bee5349f894cab2d87fe5/packages/relay-runtime/store/RelayModernStore.js).

**Comment by kmjennison** [comment]
@morrys Yeah, if I'm understanding this code correctly, it looks like the `@wora/relay-store` store doesn't save the records passed to it during instantiation [here](https://github.com/morrys/wora/blob/91f6751e0c89baf5a224433bfab61220db18815f/packages/relay-store/src/Store.ts#L38), which is different from the regular Relay Modern store.

Would it be possible to have it store initial records?

**Comment by morrys** [comment]
excellent analysis, now, wora/relay-store does not handle data initialization. For this you can open an issue in its repository :)
I'll give you more details tomorrow because now it's night in Italy :)

Thank you

**Comment by kmjennison** [comment]
Great, thanks @morrys!

Also, here's a quick fix to set the records in Next.js initEnvironment, which seems to work for now:
```
const store = new Store()
const cache = store.getSource()
Object.keys(records).forEach(key => {
  cache.set(key, records[key])
})
```

**Comment by morrys** [comment]
Nice hack;) in the issue I will share some solutions to make this simpler and closer to react-relay :)
your opinion is welcome

**Comment by morrys** [comment]
Hi @kmjennison, I saw your project and noticed a problem in the SSR with the offline-first library that I will fix over the weekend in order to release a new version :)
How about if I bring your project to the offline-examples repository?

https://github.com/morrys/wora/issues/19

**Comment by kmjennison** [comment]
@morrys Great! Sounds good.

**Comment by morrys** [comment]
Hi @kmjennison,
here you can find a [simple example project in nextjs + ssr + save initial data](https://github.com/morrys/offline-examples/tree/master/relay/nextjs) .
For any information ask as well and any advice to improve it is welcome

**Comment by morrys** [comment]
Hi @kmjennison,
last night I updated the project by adding the relay-react-offline 1.0.0-rc.1 dependency & added the use of the indexdb
I would like your opinion and then I consider the issue closed.

thanks

**Comment by morrys** [comment]
I consider this issue closed, the sample project is available in this repository:
https://github.com/morrys/offline-examples
