### ISSUE TITLE
optimisticUpdater broken when offline

### ISSUE THREAD

**Issue by caleb272** [morrys/react-relay-offline#26]
Optimistic updater in the commitMutation config seems to work while online but when the application is offline it doesn't update the UI.

**Comment by morrys** [comment]
Hi @caleb272,
can you tell me the relay-tuntime and react-relay-offline versions that you are using?

**Comment by caleb272** [comment]
"react-relay": "5.0.0"
"react-relay-offline": "^0.10.0"
"relay-compiler": "5.0.0",
"relay-compiler-language-typescript": "4.6.0",
"relay-runtime": "5.0.0",

It works if the network is cut after the app is opened but if you open the app without network it doesn't work. Im on this discord server (https://discord.gg/gb5e9xM) in the relay channel and would love to help if you can point me in the general area that functionality is implemented. I pulled the project and read some of the code already.

**Comment by morrys** [comment]
I did tests in the [example project](https://github.com/morrys/offline-examples/tree/master/relay/react-native/todo-updater) in react-native and also in your case of use works correctly.

It would be useful to have more details and / or recreate the error in the example project.

The store upgrade logics are present in the [wora/relay-offline library](https://github.com/morrys/wora/blob/master/packages/relay-offline/src/OfflineFirstRelay.ts#L105)

**Comment by morrys** [comment]
After performing several tests there seem to be problems in the refresh of the UI when the values not specified in a fragment are mutated and the query was executed using the CACHE_FIRST cache policy or executed in the offline state (policy store-only).

```
AppQuery query {
    entries {
         id
         text
    }
}
```

At the moment I suggest using a fragment as a workaround:

```
AppQuery query {
   ... Entry_entries
}
```
