### ISSUE TITLE
Typescript commitMutation type error.

### ISSUE THREAD

**Issue by caleb272** [morrys/react-relay-offline#30]
commitMutation requires RelayModernEnvironment which is not compatible with the exported Environment from react-relay-offline implementation.

You can temporarily solve this by forcing Typescript to convert the type(obviously)

**Comment by morrys** [comment]
I could add commitMutation in [wora/relay-offline](https://github.com/morrys/wora/tree/master/packages/relay-offline) to solve the problem.

For the moment I leave the open issue to evaluate alternative solutions.

**Comment by morrys** [comment]
With the new release [2.2.0](https://github.com/morrys/react-relay-offline/releases/tag/v2.2.0) the problem has been solved.
