### ISSUE TITLE
new release - supports relay v9.0.0

### ISSUE THREAD

**Issue by morrys** [morrys/react-relay-offline#34]
This issue is in progress in the following branches:
react-relay-offline: https://github.com/morrys/react-relay-offline/tree/relay-v9

wora: https://github.com/morrys/wora/tree/relay-v9 (issue https://github.com/morrys/wora/issues/31)

* [x] optimize store request identifier https://github.com/facebook/relay/pull/2985
  * at the moment I have solved the problem in @ wora/relay-store
* [X] added tests in wora/relay-store https://github.com/morrys/wora/pull/39
* [X] added tests in wora/relay-offline
* [X] added tests in wora/offline-first
* [X] added tests in wora/netinfo
* [x] support relay v8.0.0 & v9.0.0
* [x] upgrade relay-hooks
* [x] check the compatibility between the query TTL and the new Relay store data invalidation feature
* [x] added tests in react-relay-offline
* [x] eslint & prettier
* [x] CI action
* [x] release wora/relay-offline & wora/relay-store
* [x] upgrade wora/relay-offline & wora/relay-store

**Comment by alexisbronchart** [comment]
Could change to "supports relay 9.0.0" now 😊

**Comment by morrys** [comment]
hi @alexisbronchart, 
you are right :)
A small clarification, the v8 and v9 versions of relays change the internal logic of the store which in offline contexts, where the store is persisted, generate excessive use of storage space.

To avoid this problem I opened a PR https://github.com/facebook/relay/pull/2985 in the relay repository in order to optimize this logic.
Once this PR has been officially released, it will be possible to carry out the support and guarantee the same levels of efficiency.

**Comment by morrys** [comment]
Added tests in wora/relay-store https://github.com/morrys/wora/pull/39

**Comment by morrys** [comment]
This issue is in progress in the following branches:
react-relay-offline: https://github.com/morrys/react-relay-offline/tree/relay-v9

wora: https://github.com/morrys/wora/tree/relay-v9

**Comment by jesster2k10** [comment]
Has this version been released yet? I tried to install it from git with nom but it appears the `lib` directory wasn't generated beforehand

**Comment by morrys** [comment]
hi @jesster2k10,
a few days ago I created the PR https://github.com/morrys/react-relay-offline/pull/41 and released version 2.0.0-rc.4 of react-relay-offline.

Soon I will officially release version 2.0.0

**Comment by jesster2k10** [comment]
> hi @jesster2k10,
> a few days ago I created the PR #41 and released version 2.0.0-rc.4 of react-relay-offline.
> 
> Soon I will officially release version 2.0.0

I've already installed the RC and it's been working great so far. For sure worth the wait!

**Comment by morrys** [comment]
Definitely :)
I plan to release the library after Easter :)

**Comment by morrys** [comment]
today I released version 2.0.0
https://github.com/morrys/react-relay-offline/releases/tag/v2.0.0

For any problem, open an issue :)
