### ISSUE TITLE
Allow offline execution of mutations that do not modify the store

### ISSUE THREAD

**Issue by matt-dalton** [morrys/react-relay-offline#35]
I've just upgraded from 0.11.1 -> 1.0.2 (and upgraded Relay to v6 - I've also tried v7).

When I turn my connection off to test offline, on one screen I get this error `TypeError: Cannot read property 'toJSON' of undefined` from the `OfflineFirstRelay` file in `relay-offline`.

It comes from this line:
```
var sinkPublish = environment
                    .getStore()
                    .getSource()
                    ._sink.toJSON();
```

This only seems to happen on one screen, I have done some digging and can't see specifically why this would error and other screens not. I can dive into this further, but just wanted to see if there was anything obvious I've missed in the upgrade.

My `relay-offline` library in my `yarn.lock` is at the right version `"@wora/relay-offline@^2.0.4"`

I have also followed your react-native example (e.g. I've added `useRestore` above my QueryRenderer).

**Comment by morrys** [comment]
Hi @matt-dalton,
did you manage to investigate the problem?

I only answered now because I was on vacation :)

**Comment by matt-dalton** [comment]
I struggled to get to the bottom of it to be honest - but you haven't seen
that error at all? I can probably have another look next week if not

**Comment by morrys** [comment]
The mistake is strange, there seems to be no optimistic response.

Try to send me some more information:
  * creation of the environment
  * commitMutation

**Comment by morrys** [comment]
I confirm that the error is generated when the mutation has not neither optimisticResponse nor optimisticUpdater.

the offline needs to have one of the following options:
 * only optimisticResponse
 * optimisticResponse + updater
 * configs
 * optimisticUpdate

**Comment by sibelius** [comment]
Can we have a warning or a better error handling ?

**Comment by morrys** [comment]
any suggestions? I could use invariant with a link to the FAQ

**Comment by matt-dalton** [comment]
Good spot. Does Relay itself now recommend you always include one of these
options? If not, seems a bit onerous to make this mandatory - I would think
just not updating the store would be a better default?

**Comment by morrys** [comment]
In relay is not mandatory because offline mutations go in errors, without the server only the client can govern the UI.

what is the use case of this mutation?

**Comment by matt-dalton** [comment]
It just has no effect on the UI, so didn't add any kind of optimistic
response

**Comment by morrys** [comment]
I could foresee the possibility of queuing mutations that do not interact with the store ... Could you send me the mutation?

**Comment by matt-dalton** [comment]
Sure...it's a very simple one, which matches your hypothesis:
```
createMutationPromise({
        mutation: graphql`
            mutation updateScreenViewedMutation($input: UpdateScreenViewedInput!) {
                updateScreenViewed(input: $input) {
                    me {
                        dateScreenViewed
                    }
                }
            }
        `,
    })
```

As I said, we didn't bother adding in an optimisticUpdate as `dateScreenViewed` presently does nothing in the UI. But can see it's a bit pointless to return that value here.

**Comment by morrys** [comment]
these days I try to sketch its implementation and release it on the weekend :)

**Comment by morrys** [comment]
Hi @matt-dalton,
today I released [version 1.1.0](https://github.com/morrys/react-relay-offline/releases/tag/v1.1.0), let me know if there are no problems so that I close the issue :)

**Comment by matt-dalton** [comment]
Amazing - thanks Lorenzo! I'll hopefully be able to give this a go tomorrow.

**Comment by matt-dalton** [comment]
Works! Thanks again.

**Comment by morrys** [comment]
Good ;)
