### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'selector.node.name')

### ISSUE THREAD

**Issue by jesster2k10** [morrys/react-relay-offline#39]
Hey, I just tried setting up this project using react native and whenever I make the switch to `relay-react-offline` my entire app stops working and I get an error screen of death like so:

![Screenshot 2020-02-19 at 17 57 00](https://user-images.githubusercontent.com/6454286/74860834-3b3c2b00-5341-11ea-89a1-57961bab8db3.png)

My code looks something like this:

```typescript
import {Network} from 'relay-runtime'
import {RecordSource, Store, Environment} from 'react-relay-offline'
import {RelayPaginationProp} from 'react-relay'
import {useCallback} from 'react'

async function fetchQuery(operation: any, variables: Record<string, any>) {
  const response = await fetch('http://localhost:3000/graphql', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  })
  return response.json()
}

const environment = new Environment({
  network: Network.create(fetchQuery),
  store: new Store(new RecordSource()),
})
```

And my package.json file is like this (I removed the irrelevant parts)
```json
{
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.0",
    "@react-native-community/netinfo": "^5.5.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-relay": "^9.0.0",
    "react-relay-network-modern": "^4.5.0",
    "react-relay-offline": "^1.1.0",
    "relay-runtime": "^8.0.0",
  }
}
```

The error seems to arrive from the `Store.js` file and I get a typescript error also due to a type mismatch with the store property:

![Screenshot 2020-02-19 at 17 59 12](https://user-images.githubusercontent.com/6454286/74861006-8a825b80-5341-11ea-979e-26f227e1844c.png)

The transcript is:

```bash
Types of property 'retain' are incompatible.
    Type '(selector: NormalizationSelector, retainConfig?: { ttl?: number | undefined; } | undefined) => Disposable' is not assignable to type '(operation: OperationDescriptor) => Disposable'.
      Types of parameters 'selector' and 'operation' are incompatible.
        Type 'OperationDescriptor' is missing the following properties from type 'NormalizationSelector': dataID, node, variablests(2322)
RelayModernEnvironment.d.ts(32, 14): The expected type comes from property 'store' which is declared here on type 'EnvironmentConfig'
```

**Comment by jesster2k10** [comment]
I was able to trace down the error to this fragment of code in Store.js

```javascript
Store.prototype.retain = function (selector, retainConfig) {
        var _this = this;
        if (retainConfig === void 0) { retainConfig = {}; }
        var _a = retainConfig.ttl, ttl = _a === void 0 ? this._defaultTTL : _a;
        var name = selector.node.name + '.' + JSON.stringify(selector.variables);
        var dispose = function () {
            var root = _this._cache.get(name);
            if (root) {
                var newRoot_1 = tslib_1.__assign({}, root, { dispose: true });
                _this._cache.set(name, newRoot_1);
            }
            _this._scheduleGC();
        };
        var root = this._cache.get(name);
        var newRoot = {
            selector: selector,
            retainTime: !root ? Date.now() : root.retainTime,
            dispose: false,
            ttl: !root ? ttl : root.ttl,
        };
        this._cache.set(name, newRoot);
        return { dispose: dispose };
    };
```

and this line in particular:

```javascript
var name = selector.node.name + '.' + JSON.stringify(selector.variables);
```

**Comment by morrys** [comment]
Hi @jesster2k10, these problems are caused by an incompatibility with the versions of the "relay" and "netinfo" libraries.

In these issues you will find more details on why this support has not yet been provided:
https://github.com/morrys/react-relay-offline/issues/38
https://github.com/morrys/react-relay-offline/issues/34#issuecomment-588248965

Feel free to ask if you have any doubts :)

**Comment by morrys** [comment]
hi @jesster2k10,
with the latest releases both relay v9 and netinfo v5 are supported.

Update the application to react-relay-offline version 2.1.0

If you have other problems, open a new issue.

**Comment by jesster2k10** [comment]
> hi @jesster2k10,
> 
> with the latest releases both relay v9 and netinfo v5 are supported.
> 
> 
> 
> Update the application to react-relay-offline version 2.1.0
> 
> 
> 
> If you have other problems, open a new issue.

Yeah, I can confirm the issue has been resolved. Been enjoying the new release

**Comment by morrys** [comment]
Thanks for your feedback :)
