### ISSUE TITLE
Is PersistGate required.

### ISSUE THREAD

**Issue by robertpitt** [morrys/react-relay-offline#5]
Does this solution still require the need for PersistGate to make sure the hydrate is finished before the QueryRenderers's are mounted?

**Comment by morrys** [comment]
I created the "QueryRendererOffline" component to manage rehydration. Because in addition to waiting for the store, it is necessary to know the network status before executing a query.
So the PersistGate is not necessary.

**Comment by robertpitt** [comment]
Thanks :)
