### ISSUE TITLE
Array Warning: The record contains two instances of the same id

### ISSUE THREAD

**Issue by Felix-N** [morrys/react-relay-offline#50]
Hi,

I'm querying some fields and get the following warning:
```
Warning: RelayResponseNormalizer: Invalid record. 
The record contains two instances of the same id: 
`RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Njc=` with conflicting field, optionen and its values: nein,ja and nein,ja. If two fields are different but share the same id, one field will overwrite the other.
```

So far I am seeing this warning only for fields defined in Graphql as array of strings ([String]), and independent of the content.
An empty array [] throws the same error as an array of ["nein", "ja"]

The warning does not occur in 'store-only' mode.

**Comment by morrys** [comment]
Hi @Felix-N,
you can check the cause of the warning in this test case:
[warns in __DEV__ if a single response contains conflicting fields with the same id](https://github.com/facebook/relay/blob/4fadbb850efd999f309e310419b7c9f798a938db/packages/relay-runtime/store/__tests__/RelayResponseNormalizer-test.js#L2495)

**Comment by Felix-N** [comment]
Hi Morrys,

I'm not sure what you mean, could you explain?
The example test looks like it indeed has 2 entries with identical id but different content

**Comment by Felix-N** [comment]
I've trimmed down the query and response a bit. 

query:

```
query EntnahmenListQuery($probennehmer: String, $terminAb: DateTime) {
  entnahmen(probennehmer: $probennehmer, terminAb: $terminAb) {
    edges {
      node {
        id
        entnahmeprotokollDaten {
          edges {
            node {
              id
              entnahmeprotokollParameter {
                name
                optionen
              }
            }
          }
        }
      }
    }
  }
}
```

response:
```
{
	"data": {
		"entnahmen": {
			"edges": [{
				"node": {
					"id": "RW50bmFobWVuOjE0NTI2OA==",
					"entnahmeprotokollDaten": {
						"edges": [{
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NTU1",
								"entnahmeprotokollParameter": {
									"name": "Flaschen Nr. Mikro",
									"optionen": [],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MTc="
								}
							}
						}, {
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NTU2",
								"entnahmeprotokollParameter": {
									"name": "Kennzahl vorhanden",
									"optionen": ["nein", "ja"],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Njc="
								}
							}
						}, {
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NTU3",
								"entnahmeprotokollParameter": {
									"name": "Wassertemperatur",
									"optionen": [],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Mw=="
								}
							}
						}, {
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NTU4",
								"entnahmeprotokollParameter": {
									"name": "Temperaturkonstanz",
									"optionen": null,
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MjQ="
								}
							}
						}]
					}
				}
			}, {
				"node": {
					"id": "RW50bmFobWVuOjE0NTI2OQ==",
					"entnahmeprotokollDaten": {
						"edges": [{
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NDcx",
								"entnahmeprotokollParameter": {
									"name": "Flaschen Nr. Mikro",
									"optionen": [],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MTc="
								}
							}
						}, {
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NDcy",
								"entnahmeprotokollParameter": {
									"name": "Kennzahl vorhanden",
									"optionen": ["nein", "ja"],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Njc="
								}
							}
						}, {
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NDcz",
								"entnahmeprotokollParameter": {
									"name": "Wassertemperatur",
									"optionen": [],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Mw=="
								}
							}
						}, {
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NDc0",
								"entnahmeprotokollParameter": {
									"name": "Temperaturkonstanz",
									"optionen": null,
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MjQ="
								}
							}
						}]
					}
				}
			}]
		}
	}
}
```

And the warnings:
```
Warning: RelayResponseNormalizer: Invalid record. The record contains two instances of the same id: `RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MTc=` with conflicting field, optionen and its values:  and . If two fields are different but share the same id, one field will overwrite the other.

Warning: RelayResponseNormalizer: Invalid record. The record contains two instances of the same id: `RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Njc=` with conflicting field, optionen and its values: nein,ja and nein,ja. If two fields are different but share the same id, one field will overwrite the other.

Warning: RelayResponseNormalizer: Invalid record. The record contains two instances of the same id: `RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6Mw==` with conflicting field, optionen and its values:  and . If two fields are different but share the same id, one field will overwrite the other.
```

One full warning:
<details>
<summary>
Warning: RelayResponseNormalizer: Invalid record. The record contains two instances of the same id: `RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MTc=` with conflicting field, optionen and its values:  and . If two fields are different but share the same id, one field will overwrite the other.
</summary>
  | console.<computed> | @ | index.js:1
-- | -- | -- | --
  | overrideMethod | @ | react_devtools_backend.js:2273
  | printWarning | @ | warning.js:30
  | push../node_modules/fbjs/lib/warning.js.warning | @ | warning.js:51
  | _validateConflictingFieldsWithIdenticalId | @ | RelayResponseNormalizer.js:500
  | _normalizeField | @ | RelayResponseNormalizer.js:378
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | _normalizeLink | @ | RelayResponseNormalizer.js:427
  | _normalizeField | @ | RelayResponseNormalizer.js:387
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | _normalizeLink | @ | RelayResponseNormalizer.js:427
  | _normalizeField | @ | RelayResponseNormalizer.js:387
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | (anonymous) | @ | RelayResponseNormalizer.js:473
  | _normalizePluralLink | @ | RelayResponseNormalizer.js:436
  | _normalizeField | @ | RelayResponseNormalizer.js:385
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | _normalizeLink | @ | RelayResponseNormalizer.js:427
  | _normalizeField | @ | RelayResponseNormalizer.js:387
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | _normalizeLink | @ | RelayResponseNormalizer.js:427
  | _normalizeField | @ | RelayResponseNormalizer.js:387
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | (anonymous) | @ | RelayResponseNormalizer.js:473
  | _normalizePluralLink | @ | RelayResponseNormalizer.js:436
  | _normalizeField | @ | RelayResponseNormalizer.js:385
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | _normalizeLink | @ | RelayResponseNormalizer.js:427
  | _normalizeField | @ | RelayResponseNormalizer.js:387
  | _traverseSelections | @ | RelayResponseNormalizer.js:129
  | normalizeResponse | @ | RelayResponseNormalizer.js:99
  | normalize | @ | RelayResponseNormalizer.js:69
  | (instrumented RelayResponseNormalizer.normalize) | @ | RelayProfiler.js:142
  | normalizeResponse | @ | RelayModernQueryExecutor.js:1130
  | (anonymous) | @ | RelayModernQueryExecutor.js:576
  | _processResponses | @ | RelayModernQueryExecutor.js:575
  | _handleNext | @ | RelayModernQueryExecutor.js:398
  | (anonymous) | @ | RelayModernQueryExecutor.js:270
  | _schedule | @ | RelayModernQueryExecutor.js:239
  | _next | @ | RelayModernQueryExecutor.js:269
  | next | @ | RelayModernQueryExecutor.js:116
  | next | @ | RelayObservable.js:535
  | (anonymous) | @ | RelayObservable.js:190
  | next | @ | RelayObservable.js:535
  | (anonymous) | @ | RelayObservable.js:452
  | Promise.then (async) |   |  
  | (anonymous) | @ | RelayObservable.js:451
  | _subscribe | @ | RelayObservable.js:580
  | subscribe | @ | RelayObservable.js:279
  | (anonymous) | @ | RelayObservable.js:194
  | _subscribe | @ | RelayObservable.js:580
  | subscribe | @ | RelayObservable.js:279
  | Executor | @ | RelayModernQueryExecutor.js:107
  | execute | @ | RelayModernQueryExecutor.js:58
  | (anonymous) | @ | RelayModernEnvironment.js:313
  | _subscribe | @ | RelayObservable.js:580
  | subscribe | @ | RelayObservable.js:279
  | (anonymous) | @ | RelayObservable.js:216
  | _subscribe | @ | RelayObservable.js:580
  | subscribe | @ | RelayObservable.js:279
  | (anonymous) | @ | fetchQueryInternal.js:110
  | _subscribe | @ | RelayObservable.js:580
  | subscribe | @ | RelayObservable.js:279
  | QueryFetcher.fetch | @ | QueryFetcher.js:130
  | QueryFetcher.execute | @ | QueryFetcher.js:98
  | push../node_modules/react-relay-offline/lib/hooks/useQueryOffline.js.exports.useQueryOffline | @ | useQueryOffline.js:32
  | push../node_modules/react-relay-offline/lib/QueryRendererHook.js.exports.QueryRendererHook | @ | QueryRendererHook.js:8
  | renderWithHooks | @ | react-dom.development.js:14803
  | mountIndeterminateComponent | @ | react-dom.development.js:17482
  | beginWork | @ | react-dom.development.js:18596
  | beginWork$1 | @ | react-dom.development.js:23179
  | performUnitOfWork | @ | react-dom.development.js:22154
  | workLoopSync | @ | react-dom.development.js:22130
  | performSyncWorkOnRoot | @ | react-dom.development.js:21756
  | (anonymous) | @ | react-dom.development.js:11089
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11039
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js:11084
  | flushSyncCallbackQueue | @ | react-dom.development.js:11072
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21199
  | dispatchAction | @ | react-dom.development.js:15660
  | (anonymous) | @ | useRestore.js:7
  | Promise.then (async) |   |  
  | useRestore | @ | useRestore.js:7
  | EntnahmenList | @ | EntnahmenList.js:30
  | renderWithHooks | @ | react-dom.development.js:14803
  | mountIndeterminateComponent | @ | react-dom.development.js:17537
  | beginWork | @ | react-dom.development.js:18596
  | beginWork$1 | @ | react-dom.development.js:23179
  | performUnitOfWork | @ | react-dom.development.js:22154
  | workLoopSync | @ | react-dom.development.js:22130
  | performSyncWorkOnRoot | @ | react-dom.development.js:21756
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21188
  | updateContainer | @ | react-dom.development.js:24373
  | (anonymous) | @ | react-dom.development.js:24758
  | unbatchedUpdates | @ | react-dom.development.js:21903
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:24757
  | render | @ | react-dom.development.js:24840
  | ./src/index.js | @ | index.js:10
  | __webpack_require__ | @ | bootstrap:784
  | fn | @ | bootstrap:150
  | 1 | @ | serviceWorker.js:141
  | __webpack_require__ | @ | bootstrap:784
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous)
</details>

**Comment by morrys** [comment]
As you can see in the answer there are two nodes with the same id:

```
{
	"data": {
		"entnahmen": {
			"edges": [{
				"node": {
					"id": "RW50bmFobWVuOjE0NTI2OA==",
					"entnahmeprotokollDaten": {
						"edges": [{
							"node": {
								"id": "RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NTU1",
								"entnahmeprotokollParameter": {
									"name": "Flaschen Nr. Mikro",
									"optionen": [],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MTc="
								}
							}
						}, {
							
			}, {
				"node": {
					"id": "RW50bmFobWVuOjE0NTI2OQ==",
					"entnahmeprotokollDaten": {
						"edges": [{
							"node": {
								"id": "**RW50bmFobWVwcm90b2tvbGxEYXRlbjoyOTU0NDcx**",
								"entnahmeprotokollParameter": {
									"name": "Flaschen Nr. Mikro",
									"optionen": [],
									"id": "RW50bmFobWVwcm90b2tvbGxQYXJhbWV0ZXI6MTc="
								}
							}
						}, {
							
	}
}
```

**Comment by Felix-N** [comment]
hi morrys,
yes, it is the same node just linked to multiple other nodes.

**Comment by morrys** [comment]
you should open an issue in relay to point out that the check does not work correctly with arrays:
https://github.com/facebook/relay/blob/34f7c2360124c20503a3868e52a0ae9dabf1411d/packages/relay-runtime/store/RelayResponseNormalizer.js#L638

**Comment by Felix-N** [comment]
what irritated my was, that i'm only getting the warning using react-relay-offline. using only relay does not produce the warning.
same if only network mode is used.

**Comment by morrys** [comment]
This is really weird because react-relay-offline doesn't change relay-runtime behavior, especially for query execution.

**Comment by Felix-N** [comment]
could it be that it is due to how react-relay-offline restores store?
in particular that node with the array, perhaps creating it twice and hence having the compare on the array (===) fail due to being a new instance?

**Comment by morrys** [comment]
As you can see from the stack, the warning is thrown by an [internal relay-runtime function](https://github.com/facebook/relay/blob/b34f576ad9184dcc5e0d3d019073996bd7a6bafd/packages/relay-runtime/store/RelayModernQueryExecutor.js#L1304) during the processing of the query response from the server.
The function normalizes the response to be then processed in the store.

**Comment by Felix-N** [comment]
Thanks Morrys,

I've created an issue on the relay-runtime repository. I've checked again without react-relay-offline and am getting the same warning there now as well - actually no clue why it did not show before. Sorry about that.

**Comment by Felix-N** [comment]
fyi:
relay-runtime fix is pending
https://github.com/facebook/relay/issues/3161
