### ISSUE TITLE
Usage with usePreloadedQuery from relay-tools/relay-hooks.

### ISSUE THREAD

**Issue by epiqueras** [morrys/react-relay-offline#54]
Is there a way to do this?

https://github.com/relay-tools/relay-hooks/

Thanks for these great libs!

**Comment by morrys** [comment]
Hi @epiqueras,
currently this hook is not handled by the offline library.

Upon returning from vacation I will integrate it in the next release :)

**Comment by epiqueras** [comment]
Thank you! I am looking forward to it.

Enjoy your vacation 😄

**Comment by morrys** [comment]
hi @epiqueras,
I released version [2.3.0](https://github.com/morrys/react-relay-offline/releases/tag/v2.3.0) including render-as-you-fetch pattern in offline mode

**Comment by epiqueras** [comment]
Awesome! Thank you 👏 👏 👏
