### ISSUE TITLE
Support for relay-runtime ^10.1.0

### ISSUE THREAD

**Issue by apbuteau** [morrys/react-relay-offline#55]
Our project depends on react-relay-offline and it would be great to understand if there is a plan to add support for the latest release of Relay v10.0.1.  Thanks!

Relay release notes: https://github.com/facebook/relay/releases/tag/v10.0.0

**Comment by morrys** [comment]
Hi @apbuteau,
definitely. I'm on vacation now so I can't give you a precise timing but the idea is to release support for version 10.x.x in September.

**Comment by apbuteau** [comment]
Excellent!  Thank you!

**Comment by dotansimha** [comment]
Hi! Any update on this one?

**Comment by morrys** [comment]
hi @dotansimha,
I postponed the release of relay-runtime 10.x support to prioritize release [2.3.0](https://github.com/morrys/react-relay-offline/releases/tag/v2.3.0) as they were features that didn't need its support.

Right now I would prefer to wait for the relay team to integrate and release this PR https://github.com/facebook/relay/pull/3070 before releasing this feature and avoid two consecutive releases with breaking changes.

**Comment by morrys** [comment]
I just [asked for an update on the PR](https://github.com/facebook/relay/pull/3070#issuecomment-710160819), I hope they will reply soon so as to evaluate whether to wait or release support.

**Comment by morrys** [comment]
Great news, the PR has been merged.
The new version of relay should be released soon and it will be possible to adapt react-relay-offline

**Comment by morrys** [comment]
The first step to support the new version in react-relay-offline is to complete this PR in relay-hooks
https://github.com/relay-tools/relay-hooks/issues/126

**Comment by morrys** [comment]
Relay-hooks 4.0.0-rc.1released & created branch https://github.com/morrys/react-relay-offline/tree/release-3.0.0

**Comment by morrys** [comment]
Issue resolved with [react-relay-offline version 3.0.0](https://github.com/morrys/react-relay-offline/releases/tag/v3.0.0)
