### ISSUE TITLE
3.0.0 version

### ISSUE THREAD

**Issue by morrys** [morrys/react-relay-offline#56]
* [x] Support for relay-runtime 10.x.x https://github.com/morrys/react-relay-offline/issues/55
   * from a first analysis it is necessary to deprecate the support for relay 8 and relay 9 as changes have been made to the signatures of the relay store methods https://github.com/morrys/wora/pull/60
 * [x] fix relay-runtime types https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50194

**Comment by berkcoker** [comment]
How about also supporting useLazyLoadQuery?

**Comment by morrys** [comment]
Hi @berkcoker,
added your request in the checklist 👍 

As soon as I can, I'll try to integrate it

**Comment by morrys** [comment]
hi @berkcoker,
I released version [2.3.0](https://github.com/morrys/react-relay-offline/releases/tag/v2.3.0) including:
 * render-as-you-fetch with usePreloadedQuery from relay-tools/relay-hooks #54
 * issue #19
 * support useLazyLoadQuery

**Comment by morrys** [comment]
Issue resolved with [react-relay-offline version 3.0.0](https://github.com/morrys/react-relay-offline/releases/tag/v3.0.0)
