### ISSUE TITLE
Mutations Process

### ISSUE THREAD

**Issue by robertpitt** [morrys/react-relay-offline#6]
Hello,

I have a scenario that needs to be covered by our offline mutation solution and wanted to understand if the current implementation fits our needs.

We have the following requirements:
1. Mutations should be persisted before they are executed to support eventual consistency.
2. Mutations must be retried with original headers ( preserve multi-user devices )
3. The original timestamp must also be sent to the server ( for conflict resolution ).

Just wondering if you can discuss a little detail on how this implementation stacks up to those requirements, and if not, what would need to be done for it be able to support them.

Look forward to the discussion.

Rob.

**Comment by morrys** [comment]
This is an excellent topic for discussion.

* When a mutation is performed if the network status is offline, it is persisted before executing the Relay Network. Its persistence, at the moment, follows the logic of the redux-offline library.

* At the moment you can think of using a different offline storage configuration per user.

* Can you provide some more details on the third point?

This library depends a lot on redux-offline for mutation management and I am not convinced that it integrates perfectly with Relay and with all the requirements of offline management.

I was waiting for a discussion of this kind to decide whether to remove this dependency.

Thank you for opening this discussion.

**Comment by robertpitt** [comment]
> At the moment you can think of using a different offline storage configuration per user.

For us, we can avoid this scenario by having the "mutation queue" be a queue of fetch operations, containing a `url`, `method`, `body` and `headers` in the store.

This means that on a multi-user device the authentication and user context is preserved for the mutations.

> Can you provide some more details on the third point?

We came up with the idea of timestamping the requests before they are sent to the server or added to the mutation queue, this way when they eventually executed we will have the time it was intended to execute, and the time it actually executed.

We can then check a log to see if another request was executed within the offline window that mutates the same node, if it does we would reject the mutation as it conflicts with another mutation that occurs while the device was offline.

**Comment by morrys** [comment]
> For us, we can avoid this scenario by having the "mutation queue" be a queue of fetch operations, containing a url, method, body and headers in the store.

With the redux-offline library its mutation queue is provided. However, they are recovered and executed once the device returns online.
I'm thinking of replacing this library and logic to allow a customizable management and use the clientMutationId to associate mutations connected to the same node.

For the moment I would like to avoid the possibility of queuing a mutation with Network information but consider integrating multi-user management better.

> timestamping 

I entered the "effect" field with the "fetchTime" property while saving in the executed mutation queue.

**Comment by morrys** [comment]
Hi Robert,
in the latest versions I added many features that allow you to interact during the offline process.

The most useful ones for your needs are:
* `onPublish`: function that allows to insert additional information to the mutation that ends up in the offline queue.

* `network`: a different network for the execution of mutations in the queue

Now I'm working to simplify the recovery of this information during mutation execution.

I'd like to hear from you.

Thank you,
Lorenzo

**Comment by robertpitt** [comment]
Hey @morrys, Sorry I haven't been around to reply sooner, pretty busy atm, I'll take a look again in the next week or so, speak soon.

**Comment by morrys** [comment]
It took some time for this PR to be accepted facebook/relay#2937 but now it is possible to have full control of the offline process directly from the mutations.

https://github.com/morrys/react-relay-offline/releases/tag/v2.2.0
