### ISSUE TITLE
useRestore not working anymore after update to v3

### ISSUE THREAD

**Issue by alexisbronchart** [morrys/react-relay-offline#65]
Hi, I updated to v3 and running into an issue where I'm stuck in loading state at the boot of my app (react-native).
I'm using the `useRestore` hook to know if the store is rehydrated as per the docs.
`const isRehydrated = useRestore(environment)`
I'm now stuck because `isRehydrated` is always false and I don't see any errors.
I tried to console log the environment after the useRestore call : 
<img width="1231" alt="Screenshot 2021-01-27 at 17 21 51" src="https://user-images.githubusercontent.com/1279527/106020565-34c34100-60c4-11eb-82cf-d273d2291faf.png">
There seems to be something going on in promisesRestore, not sure if it's related?
Any idea of what's going on? What can I try?

**Comment by morrys** [comment]
hi @alexisbronchart,
could it be linked to this PR? https://github.com/morrys/wora/pull/77/files

You could help by debugging here:
https://github.com/morrys/wora/blob/master/packages/relay-offline/src/Environment.ts#L105

**Comment by morrys** [comment]
Soon I will release version 3.1.0 with this PR too:
https://github.com/morrys/wora/pull/76

**Comment by alexisbronchart** [comment]
> hi @alexisbronchart,
> could it be linked to this PR? https://github.com/morrys/wora/pull/77/files
> 
> You could help by debugging here:
> https://github.com/morrys/wora/blob/master/packages/relay-offline/src/Environment.ts#L105

The resulting promise defined here https://github.com/morrys/wora/blob/3fde37aff3115af50997eac8a8e2213677021692/packages/offline-first/src/index.ts#L98
seems to be the cause but not sure why. The PR will probably help. I'll try master asap.

**Comment by alexisbronchart** [comment]
I can't manage to install the master version of @wora/offline-first from the mono repo thing. What would the most straightforward way to test this?

**Comment by morrys** [comment]
The simplest way is to run the build and then copy the lib folder that is created [here](https://github.com/morrys/wora/tree/master/packages/offline-first) in place of the lib in node_modules/@wora/offline-first.
You can do the same for cache-persist .

**Comment by alexisbronchart** [comment]
Done. It works!

**Comment by morrys** [comment]
Great :)
tomorrow i plan to release the official versions of wora and react-relay-offline.

Let me know if you find any other errors

**Comment by morrys** [comment]
@alexisbronchart, fix released with [react-relay-offline 3.1.0](https://github.com/morrys/react-relay-offline/releases/tag/v3.1.0)
