### ISSUE TITLE
Multiple calls of useMutation into offline mode

### ISSUE THREAD

**Issue by gtkatakura** [morrys/react-relay-offline#69]
Hi, I have a doubt about what happens when I have multiple mutations happening into offline mode and the internet goes back online. Today I try to use the useMutation with this configuration and only the last mutation made into offline mode is synced with the server when internet goes back online. I need extra configurations to have multiple mutations into the queue to be performed when internet goes back online?

```ts
const [updateStoreCategory] = useMutation<StoreCategoryListUpdater_Mutation>(
  graphql`
    mutation StoreCategoryListUpdater_Mutation(
      $addConnections: [ID!]!
      $deleteConnections: [ID!]!
      $input: UpdateStoreCategoryInput!
    ) @raw_response_type {
      updateStoreCategory(input: $input) {
        store
          @appendNode(
            connections: $addConnections
            edgeTypeName: "StoreEdge"
          ) {
          id @deleteEdge(connections: $deleteConnections)
          category
        }
      }
    }
  `
)

const update = () => {
  updateStoreCategory({
    variables: {
      input: {
        storeId: store.id,
        category: newCategory,
      },
      deleteConnections,
      addConnections: [
        getSafeConnectionID('root', 'StoreList_stores', {
          where: { category: { eq: newCategory } },
        }),
      ],
    },
    optimisticResponse: {
      updateStoreCategory: {
        store: {
          id: store.id,
          category: newCategory,
        },
      },
    },
  })
}
```

**Comment by morrys** [comment]
Hi @gtkatakura,
what do you mean by:

> and only the last mutation made into offline mode is synced with the server when internet goes back online

When the application comes back online is only the last mutation executed in the network or all are executed and is there a problem updating the relay store?

**Comment by gtkatakura** [comment]
Only the last mutation executed in the network.

**Comment by morrys** [comment]
You can add the onError option in the mutation
```ts
onError: (e) => {
  console.log ("error", e)
}
```
and try to run mutations in offline mode again?

**Comment by gtkatakura** [comment]
Added code:

```ts

{
  onCompleted(response) {
    console.log('completed', response)
  },
  onUnsubscribe() {
    console.log('unsubscribe')
  },
  onError(error) {
    console.log('error', error)
  },
}
```

Output:
![Screenshot from 2021-03-11 13-19-40](https://user-images.githubusercontent.com/8618687/110819047-9272ad80-826c-11eb-880d-44cc72d47f43.png)

I called the mutation with three different store.id, after that I toggle the internet (offline -> online). Another store.id/category was used. I am using EnvironmentIDB (IndexedDB), maybe something wrong when trying to get data from the cache?

![Screenshot from 2021-03-11 13-21-43](https://user-images.githubusercontent.com/8618687/110819248-c057f200-826c-11eb-9fab-4c4fa15bfee8.png)

My configuration to environment:

```ts
const fetchQuery: FetchFunction = async (request, variables) => {
  if (!process.env.GATSBY_GATEWAY_GRAPHQL_URL) {
    throw new Error(
      `You should provide a GATSBY_GATEWAY_GRAPHQL_URL into your .env.${process.env.NODE_ENV}`
    )
  }

  const response = await fetch(process.env.GATSBY_GATEWAY_GRAPHQL_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: request.text,
      variables,
    }),
  })

  return response.json()
}


const environment = EnvironmentIDB.create({
  network: Network.create(fetchQuery),
})
```

**Comment by gtkatakura** [comment]
I confirmed that every time I send a mutation into offline mode, the IndexedDB adds a new key/value for this offline collection of IndexedDB, but after I toggle the internet to online mode, it isn't cleared, the offline collection stays the same, just append-only new key/value when toggle to offline mode again and run new mutations.

**Comment by morrys** [comment]
What offline options do you have?

These allow you to better debug the offline workflow:

```ts
environment.setOfflineOptions({
  network: network, //optional
  start: async mutations => {
    //optional
    console.log('start offline', mutations);
    return mutations;
  },
  finish: async (mutations, error) => {
    //optional
    console.log('finish offline', error, mutations);
  },
  onExecute: async mutation => {
    //optional
    console.log('onExecute offline', mutation);
    return mutation;
  },
  onComplete: async options => {
    //optional
    console.log('onComplete offline', options);
    return true;
  },
  onDiscard: async options => {
    //optional
    console.log('onDiscard offline', options);
    return true;
  },
  onPublish: async offlinePayload => {
    //optional
    console.log('offlinePayload', offlinePayload);
    return offlinePayload;
  },
});
```

**Comment by gtkatakura** [comment]
Oh, I added your configuration and now the mutations are correctly handled into the IndexedDB and all mutations are being executed. My bad, I read the docs and thought these options are optional.

**Comment by morrys** [comment]
@gtkatakura, you are right, they should be optional but there is a fix to do because at the moment onDiscard & onComplete are mandatory

For this I created a PR in wora: https://github.com/morrys/wora/pull/78 

thanks for the tip 👍
