### ISSUE TITLE
Refetch containers

### ISSUE THREAD

**Issue by robertpitt** [morrys/react-relay-offline#7]
Noticed on your README.md you said:

> TODO: 
> Implementation of Refetch Container Offline

Just wondering if you could expand a little more on what you think the library is missing to support Refetch Containers.

I have used createRefetchContainer in my native offline example app and seems to work ok from a first pass.

See container here: https://github.com/robertpitt/react-relay-offline-native-example/blob/feature/fragment-container-v0.2.0/src/pages/Cinimas/index.ts, ui code in Cinimas.tsx.

**Comment by morrys** [comment]
The implementation of the refetchContainer involves the management of fetchPolicy (network-only and store-or-network). To make it homogeneous with the management of the "QueryRenderer" I have to add the cache-first and offline policy.

For a better implementation of the refetchContainer I opened a PR in the Relay project "https://github.com/facebook/relay/pull/2739" and the repository "https://github.com/relay-tools/relay-hooks" where i'm recreating the react-relay components using hooks.

**Comment by morrys** [comment]
Using relay-hooks useRefetch you can use the new store-or-network & store-only policies
https://github.com/relay-tools/relay-hooks/blob/master/useRefetch.md

Furthermore, using the isOnline function of the environment, it is possible to disable the refetch or refetch with the store-only policy
