### ISSUE TITLE
environment.isRehydrated is not a function

### ISSUE THREAD

**Issue by plamenh** [morrys/react-relay-offline#71]
There's something really strange going on here.

In standard react-relay the fetchQuery function that goes into the Network constructor has the following structure:

```
function fetchQuery(
  operation,
  variables,
  cacheConfig,
)
```

The fetchQuery that comes with react-relay-offline expects the following:

`function fetchQuery(environment, taggedNode, variables, cacheConfig)`

So what am I doing wrong here? It's something with the fetchQuery for sure, but it looks to me like your documentation is not complete (There's no clarity where fetchQuery is coming from).

**Comment by morrys** [comment]
Hi @plamenh,
sorry for the delay in the response.
react-relay-offline extends react-relay's fetchQuery to rehydrate the offline environment.
However, react-relay's fetchQuery has the following signature:
```ts
function fetchQuery<T: OperationType>(
  environment: IEnvironment,
  taggedNode: GraphQLTaggedNode,
  variables: $PropertyType<T, 'variables'>,
  cacheConfig?: ?CacheConfig,
): Promise<$PropertyType<T, 'response'>> {
```
https://github.com/facebook/relay/blob/v10.1.3/packages/relay-runtime/query/fetchQuery.js#L30-L35

**Comment by plamenh** [comment]
My bad, fetchQuery in react-relay indeed has a different signature than the one I mentioned.
