### ISSUE TITLE
Is relay v11 supported?

### ISSUE THREAD

**Issue by giautm** [morrys/react-relay-offline#74]
I want to use this library with Relay v11. Is it supported?

**Comment by giautm** [comment]
Yeah, I found branch react-relay-v11.0.2 on this repo

**Comment by giautm** [comment]
Hi @morrys, can you please publish a beta version that bases on branch relay-v11.0.2? I want to use that version with my project.

**Comment by morrys** [comment]
Hi @giautm,
i plan to release the version this week (including wora 5.0.0 dependencies https://github.com/morrys/wora/pull/83) 👍

**Comment by morrys** [comment]
Hi @giautm,
i just released react-relay-offline 4.0.0-rc.2 https://github.com/morrys/react-relay-offline/pull/73

Your feedback would be useful so as to release version 4.0.0 as soon as possible 👍

**Comment by giautm** [comment]
Hi, I tried `4.0.0-rc.2` on my project then it's working fine. But I have another consent, can we remove depends on relay-hooks? Because react-relay v11 really supported hooks?

**Comment by morrys** [comment]
At the moment I prefer this package to depend on relay-hooks (created and maintained by me) as I am waiting for [the major version to be released by Relay when a future version of React is released that fully supports concurrent rendering and Suspense for Data Fetching](https://relay.dev/docs/migration-and-compatibility/suspense-compatibility/#what-does-it-mean-for-me-if-i-start-using-relay-hooks-in-react-17)

**Comment by giautm** [comment]
Good to know about that, 👍

**Comment by morrys** [comment]
issue fixed with version [4.0.0](https://github.com/morrys/react-relay-offline/releases/tag/v4.0.0)
