### ISSUE TITLE
QueryRenderer does not refresh when the store gets updated.

### ISSUE THREAD

**Issue by navilan** [morrys/react-relay-offline#8]
Thanks for the fantastic library.  We use optimistic updates and are offline heavy.  When the store gets updated as a result of a mutation, currently QueryRenderer does not refresh its data.  

I've traced it to this piece of code:
https://github.com/morrys/react-relay-offline/blob/master/src/hooks/useQuery.ts#L48

Is there a way we can signal that there are store updates so that this effect is rerun?

**Comment by morrys** [comment]
Hi navilan,
these days I'm working on optimizing mutation management.
In the "mutation" branch I have already made important changes including:
* rewriting of the original logic of mutations
* moved off-line mutation management
* fix of the publish optimistic response

The choice to customize and rewrite some basic components of react-relay derives from the fact that it does not natively provide the "cache-first" and "cache-only" policies, necessary in offline contexts.

At the same time I am opening PR on the Relay repository to centralize some logics in order to reuse their components but it is a process that takes more time.

As this is a constantly evolving library, I recommend using the tilde ~ in the version of react-relay-offline inside the package.json and following the github project I created "https://github.com/morrys/react- relay-offline / projects / 1 "(I will add a related section in the readme.me).

Suggestions on how to be alerted and updated about major changes are welcome.

thank you for your interest

**Comment by morrys** [comment]
As soon as I can I will release the beta version in the branch mutation, so you will be able to verify if this problem has been solved.

**Comment by navilan** [comment]
Excellent.  Thank you @morrys.  Will do as suggested.

**Comment by morrys** [comment]
hi navilan, I just released the 0.3.0-rc.1 version from the `mutation` branch.
From this version it is necessary to replace offline mutations
```ts
import {commitMutation, graphql} from 'react-relay';
```
with
```ts
import {commitMutation, graphql} from 'react-relay-offline';
```
all references to react-relay are included in the index file of this library.

Finally, I created a new repository where there is an example most suitable for using this library. (a couple of things still need to be fixed). https://github.com/morrys/react-relay-offline-example

I await your news if the problem of mutation still persists or if you find other problems.

**Comment by navilan** [comment]
Thank you @morrys. Will try this out today and let you know.  👍

**Comment by navilan** [comment]
@morrys : So, we tried this out today. There are few behavioral differences / perhaps anomalies that we spotted:

1) It is not sufficient to provide just the optimsticUpdater, optimisticResponse is also necessary
2) The root field with the mutation name does not contain response data
3) It appears as though the `updater` function is called instead of the `optmisticUpdater` function despite there being no server response.

Eventually, the commitUpdate fails during validation as the `sink` contains the data to be updated.
These issues arise when we do commitUpdate (from react-relay-offline) without network connection.  We will put together a barebones app or use the example repository that reproduces this problem.  

It might be easier to discuss this on slack for faster collaboration.

**Comment by morrys** [comment]
You have specified exactly the reasons that led me to create a beta version of a possible solution to the problems of offline mutations.
To make everyone participate, I will explain briefly the problem to be solved: in Relay when the "optimsticUpdater" is called it expects to temporarily mark the record in the store and I would like to avoid modifying this behavior.

At the moment I have implemented in beta the solution that I consider to be the cleanest and simplest. Use the configs and optimistic response.
It prevents developers from directly managing the store and leaving this task to the library itself.

I would be curious to know the limits of this implementation.

**Comment by navilan** [comment]
@morrys : One of our goals is to manage offline vs online completely in the network and storage layer so that application code can be completely oblivious (within reason :) ) to connectivity.  `react-relay-offline` is perfect for us to realize this goal.

We also need to use the `updater` (and as a consequence `optimisticUpdater`) functionality so that aggregations and relationships are updated even when disconnected.  We also allow selective updates (where the server returns the entire document) and having relay generate the response also makes our code base manageable. 

As an example, imagine updating username and getting back username and email from the server.  With an (optimistic)updater, we can simply update that attribute and have relay figure out what to return.  With optimistic response, we need to construct the entire object to do selective updates.

Apologies for the dense response.  Please let me know if there are things that need further clarification.

One of us will also post a fork of the examples repository to show this issue.

**Comment by VivekNeel** [comment]
Hey @morrys,

Thanks for the great work!

I have just created a fork of your example repos, and try to demonstrate this behaviour.

**With react-relay-offline**

https://github.com/VivekNeel/react-relay-offline-example/commit/0ea273b74c38cf140b617d88aa2db802f70eb86b

**With react-relay**

https://github.com/VivekNeel/react-relay-offline-example/commit/8a18f72b60166c3dea5a321b6ae5e3ff66bd3f98

**Comment by morrys** [comment]
Hi VivekNeel,
We are dealing with one of the main issues of offline management and it will certainly be necessary to evaluate several options.
First I would like to find a simple way to share via gist or example project of a real case in which this solution is not sufficient to map all the needs.

This counter solution certainly has the need to rewrite part of the applications that use it but it is a price that can be paid if the result is the uniformity of use of the application between online and offline.

**Comment by morrys** [comment]
Hi navilan,
sorry but I don't understand this passage well "With optimistic response, we need to construct the entire object to do selective updates."
It would be useful to see, even a pseudo code, of such cases.

**Comment by sibelius** [comment]
Check here https://medium.com/entria/relay-modern-optimistic-update-a09ba22d83c9

**Comment by morrys** [comment]
For more reflection, I add:

The Updater Configs as per documentation provide an array on how to use the response from each mutation to update the client-side store. We do this by configuring the mutation with one or more of the following config types:

NODE_DELETE
RANGE_ADD
RANGE_DELETE

While the only modification of the fields takes place automatically in Relay Modern.

I find them very complete as well as being objects that in the future can be used and persisted in the offline cache of mutations.

**Comment by navilan** [comment]
Hi Lorenzo,

Here is a simple but slightly contrived example.  We can also talk offline where we can share some private code if this is not adequate.

```graphql
input ItemInput {
  name: String
  description: String
}

type Item {
  id: ID!
  name: String!
  description: String!
}

type query {
  getItem(itemId: ID!): Item
}

type Mutation {
  createItem(id: ID, item: ItemInput!): Item
  updateItem(id: ID!, item: ItemInput!): Item
}

schema {
  query: Query
  mutation: Mutation
}
```

1. You can see how `updateItem` allows us to update _only_ parts of the object, (name or description) but expects the entire `Item` to be returned.  Using the `optimisticUpdater` without the `optimisticResponse` allows us to update just that attribute.
2. Also in `createItem` you can see that (if it were to work completely offline), it will have to update the store so that `getItem` works with that id. We use updater to push to store for this optimization.

We'd really like to not lose out on using `updater` and `optmisticUpdater` as we see a lot of use for us in the short and long term where it benefits us to have access to the store.

Hope this gives a little bit of clarity.  If not, we can get on slack and see how we can discuss it in the context of some real code.

**Comment by morrys** [comment]
This situation is similar to the `ChangeTodoStatusMutation` mutation of the example project, or am I wrong?

In these days I will examine better the react-relay library to understand which internal api need to be modified to make the best use of the optimisticUpdate.
So as to have more details on the feasibility and the consequent risk.

**Comment by navilan** [comment]
> This situation is similar to the `ChangeTodoStatusMutation` mutation of the example project, or am I wrong?

The only difference is that, whereas the `ChangeTodoStatusMutation` has a specific response corresponding to the mutation, the `updateItem` response returns the entire `Item`.  

The ideal situation would be that react-relay-offline and relay work identically when it comes to `updater` and `optimisticUpdater`.

**Comment by morrys** [comment]
at last, in the readme I had written this requirement
"When a new node was created by mutation the id must be generated in the browser to use it in the optimistic response"

This in all the scenarios that we hypothesize is recommended to manage successive mutations on the same record in the same offline session.

Example: I create a todo and modify its status in two different mutation, if the server-side id is generated the modification mutation is performed on an incorrect id.

**Comment by navilan** [comment]
Absolutely @morrys .   We came to the same conclusion as well that the client should be responsible for the identifiers.

**Comment by navilan** [comment]
Relay does a rollback and redo the update - but given a scenario where the application is largely offline, it is an acceptable (at least for our purposes) that the client has control over identifiers.
